export const ROUTES = [
  {
    id: 'home',
    bundle: 'src/bundles/home.bundle.html',
    source: 'src/generated/home.dc.html',
    out: 'index.html',
    canonical: 'https://mavebuild.com/',
    title: 'Architect-Designed ADU & Modular Home Kits | MAVE',
    description: 'Architect-led ADUs delivered as build-ready plans, permits and materials. Five modular home and cabin kits starting at $41,990.',
    schemaType: 'WebSite',
    minText: 2000,
  },
  {
    id: 'hearth-studio',
    source: 'src/models/hearth-studio.dc.html',
    out: 'models/hearth-studio/index.html',
    canonical: 'https://mavebuild.com/models/hearth-studio',
    title: 'Hearth Studio — 375 sq ft ADU Modular Home | MAVE BUILD',
    description: 'A 375 sq ft studio ADU with kitchen, bath, living and sleeping in one footprint, starting at $65,000. Rental-ready, sleeps 1–2.',
    product: { name: 'Hearth Studio', price: 65000, floorSize: 375 },
    minText: 1000,
  },
  {
    id: 'grove-studio',
    bundle: 'src/bundles/grove-studio.bundle.html',
    source: 'src/generated/grove-studio.dc.html',
    out: 'models/grove-studio/index.html',
    canonical: 'https://mavebuild.com/models/grove-studio',
    title: 'Grove Studio — Loft Cabin for Campgrounds & Glamping | MAVE BUILD',
    description: 'A 320 sq ft loft cabin built for camping and outdoor retreats, starting at $69,000. Sleeps up to four, ideal for glamping sites, ADU and Airbnb hosts.',
    product: { name: 'Grove Studio', price: 69000, floorSize: 320 },
    minText: 1000,
  },
  {
    id: 'hearth-one-bedroom',
    bundle: 'src/bundles/hearth-one-bedroom.bundle.html',
    source: 'src/generated/hearth-one-bedroom.dc.html',
    out: 'models/hearth-one-bedroom/index.html',
    canonical: 'https://mavebuild.com/models/hearth-one-bedroom',
    title: 'Hearth · One Bedroom ADU Modular Home | MAVE BUILD',
    description: 'A one-bedroom ADU with dedicated bedroom and full bath, starting at $84,000. 480 sq ft, permit-ready, sleeps 2–4.',
    product: { name: 'Hearth One Bedroom', price: 84000, floorSize: 480 },
    minText: 1000,
  },
  {
    id: 'hearth-pod',
    bundle: 'src/bundles/hearth-pod.bundle.html',
    source: 'src/generated/hearth-pod.dc.html',
    out: 'models/hearth-pod/index.html',
    canonical: 'https://mavebuild.com/models/hearth-pod',
    title: 'Hearth Pod — Backyard Space for Work and Retreat | MAVE BUILD',
    description: 'A 167 sq ft all-purpose backyard structure, starting at $41,990. One clear room, permit-ready — ideal for a home office, studio or guest space.',
    product: { name: 'Hearth Pod', price: 41990, floorSize: 167 },
    minText: 1000,
  },
  {
    id: 'grove-pod',
    bundle: 'src/bundles/grove-pod.bundle.html',
    source: 'src/generated/grove-pod.dc.html',
    out: 'models/grove-pod/index.html',
    canonical: 'https://mavebuild.com/models/grove-pod',
    title: 'Grove Pod — Garden Cabin for Camping & Outdoor Retreats | MAVE BUILD',
    description: 'A 182 sq ft garden cabin with a full bath, starting at $52,990. Compact and fast to build — ideal for backyard studios, guest space or rental income.',
    product: { name: 'Grove Pod', price: 52990, floorSize: 182 },
    minText: 1000,
  },
  {
    id: 'resources',
    bundle: 'src/bundles/resources.bundle.html',
    source: 'src/generated/resources.dc.html',
    out: 'resources/index.html',
    canonical: 'https://mavebuild.com/resources',
    title: 'ADU & Modular Home Guides | MAVE',
    description: 'Practical, jargon-free guides on cost, permitting, and the modular build process for ADU and backyard cabin projects.',
    schemaType: 'CollectionPage',
    minText: 500,
  },
  {
    id: 'modular-adu-cost',
    bundle: 'src/bundles/modular-adu-cost.bundle.html',
    source: 'src/generated/modular-adu-cost.dc.html',
    out: 'resources/how-much-does-a-modular-adu-cost/index.html',
    canonical: 'https://mavebuild.com/resources/how-much-does-a-modular-adu-cost',
    title: 'How Much Does a Modular ADU Cost in NY, OR & CA? | MAVE',
    description: 'A complete breakdown of the seven cost categories behind a modular ADU or cabin project — materials, design, permits, foundation, utilities, delivery and site work — with regional price ranges for NY, OR and CA.',
    schemaType: 'Article',
    minText: 1500,
  },
];
